### ISSUE TITLE
I/O, File, and Network API

### ISSUE THREAD

**Issue by azjezz** [azjezz/psl#28]
- [x] IO handles ( done - #127 )
  - [x] File handles ( done - #250 )
  - [x] Network handles ( done - #257 )
    - [x] Socket handle
    - [x] Server Interface
    - [x] TCP
      - [x] TCP Sockets
      - [x] TCP Server
    - [x] UDP
      - [x] UDP Sockets
      - [x] UDP Server

**Comment by HenkPoley** [comment]
Accidentally stumbling onto this. Would the I/O addition allow one to keep read and write access more clearly separate? E.g. an API with a cache backing (cache _reads_) for speed, and in another part validation (database _reads_) as a first step, before _writing_ out data. A bit akin to the Haskell I/O monad (which I am _not_ very familiar with).

Of course with backing from Psalm, since PHP doesn't care.

**Comment by azjezz** [comment]
see #127 

for now, we want to have basic IO handles, later add support for Files and Network ( Sockets, Servers .. etc )

**Comment by azjezz** [comment]
@HenkPoley FYI, File API has been implemented in #250, network/tcp/udp are in the work #257.
